import type { CalendarEvent } from "../types";

// Outlook-style local samples. Replace this file with Microsoft Graph or connector reads later.
export const sampleCalendarEvents: CalendarEvent[] = [
  {
    id: "CAL-001",
    title: "Shoot: DAY IN THE LIFE | Anatomy of a Session",
    projectName: "Anatomy of a Session | Day In The Life",
    type: "Shoot",
    start: "2026-03-06T10:00:00",
    end: "2026-03-06T14:00:00",
    location: "EAST 43RD",
    attendees: ["Mitch Bernier"],
    status: "Busy",
    source: "Production queue",
  },
  {
    id: "CAL-002",
    title: "Edit Block: Programming Portal Assets",
    projectName: "Programming Portal Assets",
    type: "Post-Production",
    start: "2026-03-18T09:30:00",
    end: "2026-03-18T13:00:00",
    location: "Post Production",
    attendees: ["Lindsay", "Arlen", "Danielle", "Mitch"],
    status: "Busy",
    source: "Outlook sample",
  },
  {
    id: "CAL-003",
    title: "Shoot: CPT & Close",
    projectName: "CPT & Close",
    type: "Shoot",
    start: "2026-04-03T11:00:00",
    end: "2026-04-03T15:00:00",
    location: "East 92nd, Dumbo, Gramercy",
    attendees: ["Mitch Bernier", "Ashley Hudson"],
    status: "Busy",
    source: "Production queue",
  },
  {
    id: "CAL-004",
    title: "Shoot: Modular Assessment",
    projectName: "Modular Assessment Shoot",
    type: "Shoot",
    start: "2026-04-08T14:00:00",
    end: "2026-04-08T16:00:00",
    attendees: ["Lindsay", "Craige"],
    status: "Busy",
    source: "Production queue",
  },
  {
    id: "CAL-005",
    title: "Production Hold: Sales Training Asset",
    projectName: "Sales Training Asset",
    type: "Hold",
    start: "2026-04-29T10:00:00",
    end: "2026-04-29T12:00:00",
    location: "HQ | Experience room",
    attendees: ["Production Lead"],
    status: "Tentative",
    source: "Outlook sample",
  },
  {
    id: "CAL-006",
    title: "Edit Review: Coach Curriculum Evolution Arc",
    projectName: "Coach Curriculum Evolution Arc",
    type: "Review",
    start: "2026-05-01T13:00:00",
    end: "2026-05-01T14:00:00",
    location: "Teams",
    attendees: ["L&D", "Production Lead"],
    status: "Busy",
    source: "Outlook sample",
  },
];
